# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :mail => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
      },
    }

    Vagrant.configure("2") do |config|

      MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
		      box.vm.host_name = boxname.to_s

          boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
          end
          
          if boxconfig.key?(:public)
            box.vm.network "public_network", boxconfig[:public]
          end

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y traceroute net-tools tcpdump nano  
          SHELL
        
		      case boxname.to_s
		      when "mail"
			      box.vm.provision "shell", inline: <<-SHELL
              yum install -y wget mlocate bind-utils telnet mailx sharutils                   
              yum install epel-release -y
              yum install -y http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm
              wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
              rpm -Uvh remi-release-7*.rpm
              yum update -y
              sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
              yum install ntp -y
              ntpdate ntp5.stratum2.ru
              systemctl enable ntpd
              systemctl start ntpd
              yum --enablerepo=remi install mariadb-server -y
              systemctl enable mariadb
              systemctl start mariadb
              mysql -e "CREATE USER 'postfix'@'localhost' IDENTIFIED BY 'mypassword';"
              mysql -e "CREATE DATABASE postfix;"
              mysql -e "GRANT ALL PRIVILEGES ON postfix.* TO postfix;"
       #           yum -y install clamav-server clamav-data clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd
              wget https://github.com/Haran/Mail.CONF/blob/master/opt/mysql_dump.sql
              mysqldump postfix < mysql_dump.sql

### кусок копирования настроек клама
#                  mv /etc/clamd.d/scan.conf{,.default}
 #                 cp /vagrant/configs/clamav/scan.conf /etc/clam.d/
  #                mv /etc/freshclam.conf{,.default} 
   #               cp /vagrant/configs/clamav/freshclam.service /usr/lib/systemd/system/
    #              setsebool -P antivirus_can_scan_system 1
     #             setsebool -P clamd_use_jit 1
### конец куска копирования настроек клама

      ### почему-то не стартует клам
      #            freshclam
        #          systemctl start freshclam
         #         systemctl enable freshclam
          #        systemctl start clamd@scan
           #       systemctl enable clamd@scan
      ### поэтому кусок закоменнтирован

              yum install dovecot dovecot-mysql -y
              groupadd  -g 1100 vmail
              useradd -d /var/vmail/ -g 1100 -u 1100 vmail
              chown vmail:vmail /var/vmail
              mkdir /etc/postfix/certs
              openssl req -new -x509 -days 3650 -nodes -out /etc/postfix/certs/cert.pem -keyout /etc/postfix/certs/key.pem
              mkdir /etc/postfix/mysql













                SHELL
        
        end

      end

  end

end
