# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :mail => {
        :box_name => "centos/6",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
      },
    }

    Vagrant.configure("2") do |config|

      MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
		      box.vm.host_name = boxname.to_s

          boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
          end
          
          if boxconfig.key?(:public)
            box.vm.network "public_network", boxconfig[:public]
          end

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
          end

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y traceroute net-tools tcpdump nano  
          SHELL
        
		      case boxname.to_s
		      when "mail"
			      box.vm.provision "shell", inline: <<-SHELL
                  yum install epel-release -y
                  um -y install http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm                  yum install -y http://centos.alt.ru/pub/repository/centos/6/x86_64/centalt-release-6-1.noarch.rpm
                  wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
                  rpm -Uvh remi-release-6.rpm
                  yum install -y wget mlocate bind-utils telnet mailx sharutils 
                  yum update -y
                  setenforce permissive
                  yum install ntp
                  ntpdate ntp5.stratum2.ru
                  chkconfig ntpd on && /etc/init.d/ntpd start
                  yum --enablerepo=remi install mysql-server -y
                  service mysqld star
                  chkconfig mysqld on
                  mysql -e 'CREATE USER postfix@localhost IDENTIFIED BY 'mypassword';'
                  mysql -e 'CREATE DATABASE postfix;'
                  mysql -e 'GRANT ALL PRIVILEGES ON postfix.* TO postfix;'














                SHELL
        
        end

      end

  end

end
