# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :zabbix => {
        :box_name => "centos/7",
	    :box_version => "1804.02",
        :ip_addr => '192.168.12.100'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      
#      box.vm.network "forwarded_port", guest: 2000, host: 2000
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
      end
      
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        sed -i '7s/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
        rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
        
        yum install -y epel-release nano nginx net-tools
        systemctl stop firewalld
        systemctl disable firewalld
        systemctl start nginx
        systemctl enable nginx
        rpm -Uhv http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        yum install -y yum-utils
        yum-config-manager --enable remi-php71
        yum install -y php71 php-fpm php-cli php-mysql php-gd php-ldap php-odbc php-pdo php-pecl-memcache php-pear php-xml php-xmlrpc php-mbstring php-snmp php-soap php-bcmath
        systemctl start php-fpm
        systemctl enable php-fpm
        # netstat -tunlp | grep php-fpm       # was in how-to install zabbix, checks working php-fpm on port 9000
        cp /vagrant/www.conf /etc/php-fpm.d/www.conf
        # ll /var/run/php-fpm/php-fpm.sock    # # was in how-to install zabbix, checks started socket
        cp /vagrant/mariadb.repo /etc/yum.repos.d/mariadb.repo
        yum install -y MariaDB-server MariaDB-client
        systemctl start mariadb
        systemctl enable mariadb

        #здесь надо продолжить делать по первой статье из мануалов





      SHELL
    
    end
  end

end

