
# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
:inetrouter => {
        :box_name => "centos/6",
#        :box_name => "centos/7",
#        :box_version => "1804.02",
                :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },

  :centralrouter => {
        :box_name => "centos/7",
#        :box_version => "1804.02",
        :net => [
                  {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                  {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                  {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
                ]
  },

  :centralserver => {
        :box_name => "centos/7",
#        :box_version => "1804.02",
        :net => [
                  {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: true},
                  {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :office1router => {
        :box_name => "centos/7",
#        :box_version => "1804.02",
        :net => [
                  {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-net"},
                  {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test-net"},
                  {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                  {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                ]
  },

  :office1server => {
        :box_name => "centos/7",
#        :box_version => "1804.02",
        :net => [
                  {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: true},

                ]
  },

  :office2router => {
    :box_name => "centos/7",
#    :box_version => "1804.02",
    :net => [
                  {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                  {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
                  {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test-net"},
                  {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw-net"},
                ]
  },

  :office2server => {
    :box_name => "centos/7",
#    :box_version => "1804.02",
    :net => [
             {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev-net"},
             {adapter: 3, auto_config: false, virtualbox__intnet: true},
            ]
  },

}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", run: "always", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install -y traceroute net-tools tcpdump nano
        SHELL
        
        case boxname.to_s
        when "inetrouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
#              iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP    ## blocking zero-packets
#              iptables -A INPUT -p tcp ! --syn -m state --state NEW -j DROP   ## blocking syn-flood
#              iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP    ## blocking XMAS-packets
#              iptables -t nat -A POSTROUTING -s 192.168.0.0/22 -d 10.0.2.0/28 -o eth0 -j MASQUERADE
              echo 'net.ipv4.conf.all.forwarding=1' >> /etc/sysctl.conf
              echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
              sysctl --system
              sysctl -p
              iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
              iptables-save > /etc/iptables.conf
              echo "192.168.0.0/16 via 192.168.255.2" > /etc/sysconfig/network-scripts/route-eth1
              service network restart
            SHELL

        when "centralrouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo 'net.ipv4.conf.all.forwarding=1' >> /etc/sysctl.conf
            echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
            sysctl --system
            sysctl -p
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            cp /etc/sysconfig/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts/ifcfg-eth1:0
            sed -i 's/192\.168\.255\.2/192.168.255.5/g' /etc/sysconfig/network-scripts/ifcfg-eth1:0
            sed -i 's/eth1/eth1\:0/g' /etc/sysconfig/network-scripts/ifcfg-eth1:0
            cp /etc/sysconfig/network-scripts/ifcfg-eth1 /etc/sysconfig/network-scripts/ifcfg-eth1:1
            sed -i 's/192\.168\.255\.2/192.168.255.9/g' /etc/sysconfig/network-scripts/ifcfg-eth1:1
            sed -i 's/eth1/eth1\:1/g' /etc/sysconfig/network-scripts/ifcfg-eth1:1
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            echo "192.168.2.0/24 via 192.168.255.5" >  /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.1.0/24 via 192.168.255.9" >> /etc/sysconfig/network-scripts/route-eth1
            systemctl restart network
          SHELL
        when "centralserver"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
            SHELL
        when "office1router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo 'net.ipv4.conf.all.forwarding=1' >> /etc/sysctl.conf
            echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
            sysctl --system
            sysctl -p
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
          SHELL
        when "office1server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
            SHELL

        when "office2router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo 'net.ipv4.conf.all.forwarding=1' >> /etc/sysctl.conf
            echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
            sysctl --system
            sysctl -p
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            iptables -t nat -A POSTROUTING ! -d 192.168.1.0/24 -o eth1 -j MASQUERADE
            iptables-save > /etc/iptables.conf
            systemctl restart network
          SHELL

        when "office2server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
              echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
            SHELL

        end

      end

    end
    
end
