# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :master => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :box_check_update => "false",
        :ip_addr => '192.168.20.101'
        },
    
    :slave => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :box_check_update => "false",
        :ip_addr => '192.168.20.102'
        },
    }

Vagrant.configure(2) do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "1024"]
                    needsController = false
            end

        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            setenforce 0
            yum install -y epel-release wget
        SHELL

        case boxname.to_s
            when "master"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y http://www.percona.com/downloads/percona-release/redhat/1.0-6/percona-release-1.0-6.noarch.rpm
            yum install -y  Percona-Server-server-57
            cp /vagrant/conf/conf.d/* /etc/my.cnf.d/
            systemctl enable --now mysqld


            SHELL

#        case boxname.to_s
            when "slave"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y http://www.percona.com/downloads/percona-release/redhat/1.0-6/percona-release-1.0-6.noarch.rpm
            yum install -y  Percona-Server-server-57
            cp /vagrant/conf/conf.d/* /etc/my.cnf.d/
            sed -i 's/server-id = 1/server-id = 2/g' /etc/my.cnf.d/01-base.cnf
            sed -i 's/#replicate-ignore-table=bet.events_on_demand/replicate-ignore-table=bet.events_on_demand/g' /etc/my.cnf.d/01-base.cnf
            sed -i 's/#replicate-ignore-table=bet.v_same_event/replicate-ignore-table=bet.v_same_event/g' /etc/my.cnf.d/01-base.cnf
            
            systemctl enable --now mysqld


            SHELL

            end

        end

    end

end
