# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
    config.vm.box_version = "1804.02"
    config.vm.box_check_update = false
#    config.vm.network "forwarded_port", guest: 80, host: 8080
#    config.vm.synced_folder "../data", "/vagrant_data"
    config.vm.provision "shell", inline: <<-SHELL
#    set -x    # this is for defugging
#    yum update -y && yum upgrade -y
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
      systemctl restart sshd
      sed -i '7s/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
      sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      yum install -y epel-release nano net-tools
      systemctl stop firewalld
      systemctl disable firewalld
#    reboot
    SHELL

  config.vm.define "web", primary: true do |web|
    web.vm.hostname = 'web'
    web.vm.network "forwarded_port", guest: 22, host: 4000
    web.vm.network "public_network", ip: "192.168.12.100"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    
    web.vm.provision "shell", inline: <<-SHELL
# input provision for this VM here
    SHELL
    
    end

  end

  config.vm.define "log1" do |log1|
    log1.vm.hostname = 'log1'
    log1.vm.network "forwarded_port", guest: 22, host: 4010
    log1.vm.network "public_network", ip: "192.168.112.110"
    log1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"

    log1.vm.provision "shell", inline: <<-SHELL
# input provision for this VM here
    SHELL
  
    end
     
  end

    config.vm.define "log2" do |log2|
      log2.vm.hostname = 'log2'
      log2.vm.network "forwarded_port", guest: 22, host: 4020
      log2.vm.network "public_network", ip: "192.168.112.120"
      log2.vm.provider "virtualbox" do |vb|
        vb.memory = "512"

      log2.vm.provision "shell", inline: <<-SHELL
# input provision for this VM here
    SHELL
    
    end

  end

end
