# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :web => {
        :box_name => "centos/7",
	    :box_version => "1804.02",
        :ip_addr => '192.168.12.100'
    },
    :log1 => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.12.110'
    },
    :log2 => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.12.110'
    }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      
#      box.vm.network "forwarded_port", guest: 2000, host: 2000
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512"]
      end
      
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        sed -i '7s/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
#        rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
        yum install -y epel-release nano net-tools
        systemctl stop firewalld
        systemctl disable firewalld

      SHELL
    
    end
  end

end

