# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {

  :ABR1 => {
    :box_name => "centos/7",
    :net => [
              {adapter: 2, auto_config: false, virtualbox__intnet: "vlan12"},
              {adapter: 3, auto_config: false, virtualbox__intnet: "vlan16"},
              {ip: '10.0.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR0"},
            ]
  }, 

  :ABR2 => {
    :box_name => "centos/7",
    :net => [
              {adapter: 2, auto_config: false, virtualbox__intnet: "vlan12"},
              {adapter: 3, auto_config: false, virtualbox__intnet: "vlan20"},
              {ip: '10.0.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR1"},
            ]
  }, 

  :ABR3 => {
    :box_name => "centos/7",
    :net => [
              {adapter: 2, auto_config: false, virtualbox__intnet: "vlan16"},
              {adapter: 3, auto_config: false, virtualbox__intnet: "vlan20"},
              {ip: '10.0.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "AR2"},
            ]
  }, 


}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      
    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s

          when "ABR1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setenforce 0
              yum install -y quagga traceroute nano
              cp /vagrant/network-scripts/ABR1-ifcfg-vlan12 /etc/sysconfig/network-scripts/ifcfg-vlan12
              cp /vagrant/network-scripts/ABR1-ifcfg-vlan16 /etc/sysconfig/network-scripts/ifcfg-vlan16
              cp /vagrant/configs/daemons /etc/quagga/daemons
              cp /vagrant/configs/ABR1-zebra.conf /etc/quagga/zebra.conf
              cp /vagrant/configs/ABR1-ospfd.conf /etc/quagga/ospfd.conf
              chown quagga:quagga /etc/quagga/ospfd.conf
              chown quagga:quagga /etc/quagga/zebra.conf
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf    # если поставить 1, то не будет работать
              systemctl restart network
              systemctl enable zebra
              systemctl start zebra
              systemctl enable ospfd
              systemctl start ospfd
              SHELL
          
        when "ABR2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setenforce 0
              yum install -y quagga traceroute nano
              cp /vagrant/network-scripts/ABR2-ifcfg-vlan12 /etc/sysconfig/network-scripts/ifcfg-vlan12
              cp /vagrant/network-scripts/ABR2-ifcfg-vlan20 /etc/sysconfig/network-scripts/ifcfg-vlan20
              cp /vagrant/configs/daemons /etc/quagga/daemons
              cp /vagrant/configs/ABR2-zebra.conf /etc/quagga/zebra.conf
              cp /vagrant/configs/ABR2-ospfd.conf /etc/quagga/ospfd.conf
              chown quagga:quagga /etc/quagga/ospfd.conf
              chown quagga:quagga /etc/quagga/zebra.conf              
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
              systemctl restart network
              systemctl enable zebra
              systemctl start zebra
              systemctl enable ospfd
              systemctl start ospfd
              SHELL
          
        when "ABR3"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              setenforce 0
              yum install -y quagga traceroute nano
              cp /vagrant/network-scripts/ABR3-ifcfg-vlan16 /etc/sysconfig/network-scripts/ifcfg-vlan16
              cp /vagrant/network-scripts/ABR3-ifcfg-vlan20 /etc/sysconfig/network-scripts/ifcfg-vlan20
              cp /vagrant/configs/daemons /etc/quagga/daemons
              cp /vagrant/configs/ABR3-zebra.conf /etc/quagga/zebra.conf
              cp /vagrant/configs/ABR3-ospfd.conf /etc/quagga/ospfd.conf
              chown quagga:quagga /etc/quagga/ospfd.conf
              chown quagga:quagga /etc/quagga/zebra.conf
              echo net.ipv4.conf.all.forwarding=1  >> /etc/sysctl.conf
              echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
              echo net.ipv4.conf.all.rp_filter=0 >> /etc/sysctl.conf
              systemctl restart network
              systemctl enable zebra
              systemctl start zebra
              systemctl enable ospfd
              systemctl start ospfd
              SHELL

        end

      end

  end
  
end
